version: '3.2'
services:
  mongodb:
    image: mongo
    container_name: weather-crawler-mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    #  - ./data/:/data/db/
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: carson
      MONGO_INITDB_ROOT_PASSWORD: 0xdeadbeef
      MONGO_INITDB_DATABASE: weather_crawler

  mongodb-express:
    image: mongo-express
    container_name: weather-crawler-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: carson
      ME_CONFIG_MONGODB_ADMINPASSWORD: 0xdeadbeef
      ME_CONFIG_MONGODB_SERVER: mongodb
